# Does and/or CAN the name be updated?
name: Navify
version: 0.5.0
description: Navigation with NFC tags


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  flutter_bluetooth_serial_ble: ^0.5.0
  sliding_up_panel: ^2.0.0+1
  flutter_inappwebview: ^6.0.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  html: ^0.15.4
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/hero.png
